try {
	fn();
} catch {
	console.log("error");
}