try {
	throw "Error";
} catch (e) {
    
} catch (e) {
    
}